import { LABEL_SIZES, STYLES, validateUpload, validateLabelText, safeText, filenameFor } from './labels.js';

const $=s=>document.querySelector(s); const form=$('#label-form'); let file=null, source=null, selected='colorido', generated=[];
const palettes={colorido:['#ffdf67','#ff8ca1','#7755d9'],kawaii:['#ffe8f1','#cdbcf6','#815c8c'],escolar:['#bce9dc','#ffd768','#335a68'],minimalista:['#f4f0e9','#d9d2c7','#29252a'],floral:['#fae3e5','#afcfb2','#744959'],gamer:['#19162d','#00e1d3','#f35ac7'],espaco:['#16163c','#5954ba','#fff07b'],personalizado:['#e5dbfa','#9adfd5','#59419a']};

STYLES.forEach(([id,icon,name],i)=>{const b=document.createElement('button');b.type='button';b.className='style-card'+(!i?' selected':'');b.dataset.id=id;b.innerHTML=`<span>${icon}</span>${name}`;b.onclick=()=>{selected=id;document.querySelectorAll('.style-card').forEach(x=>x.classList.toggle('selected',x===b));$('#custom-wrap').hidden=id!=='personalizado'};$('#styles').append(b)});
const choose=()=>$('#image').click(); $('#dropzone').onclick=choose; $('#dropzone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};
$('#dropzone').ondragover=e=>e.preventDefault(); $('#dropzone').ondrop=e=>{e.preventDefault();setFile(e.dataTransfer.files[0])}; $('#image').onchange=e=>setFile(e.target.files[0]);
function setFile(next){const error=validateUpload(next);$('#image-error').textContent=error;if(error)return;file=next;const reader=new FileReader();reader.onload=()=>{source=reader.result;$('#upload-preview').src=source;$('#dropzone').classList.add('has-image')};reader.readAsDataURL(file)}
$('#label-text').oninput=e=>$('#counter').textContent=`${e.target.value.length}/32`;
function imageFrom(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.clip()}
async function compose(size, background, bleed){
  const canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const c=canvas.getContext('2d');const [a,b,ink]=palettes[selected];rounded(c,0,0,size.width,size.height,Math.max(12,size.height*.08));
  const g=c.createLinearGradient(0,0,size.width,size.height);g.addColorStop(0,a);g.addColorStop(1,b);c.fillStyle=g;c.fillRect(0,0,size.width,size.height);
  c.globalAlpha=.2;c.fillStyle=ink;for(let x=-20;x<size.width;x+=Math.max(45,size.width/7)){c.beginPath();c.arc(x,(x*1.7)%size.height,Math.max(8,size.height*.07),0,Math.PI*2);c.fill()}c.globalAlpha=1;
  const img=await imageFrom(background||source);const compact=size.id==='p';const photoW=compact?size.height*.72:size.width*(size.id==='g'?.37:.4);const pad=bleed?Math.round(size.width*(2/(size.id==='p'?30:size.id==='m'?40:70))):0;const x=pad+Math.max(8,size.width*.025),y=pad+Math.max(8,size.height*.06),h=size.height-y*2;
  c.save();rounded(c,x,y,photoW,h,size.id==='p'?h/2:Math.min(42,h*.22));const scale=Math.max(photoW/img.width,h/img.height);c.drawImage(img,x+(photoW-img.width*scale)/2,y+(h-img.height*scale)/2,img.width*scale,img.height*scale);c.restore();
  const tx=x+photoW+size.width*.04, available=size.width-tx-pad-size.width*.04;c.fillStyle=ink;c.textAlign='center';c.textBaseline='middle';let fs=Math.floor(size.height*(compact?.25:.17));const text=safeText($('#label-text').value);c.font=`700 ${fs}px Arial, sans-serif`;while(c.measureText(text).width>available&&fs>15){fs--;c.font=`700 ${fs}px Arial, sans-serif`}c.shadowColor='#fff';c.shadowBlur=Math.max(3,fs*.12);c.fillText(text,tx+available/2,size.height/2);c.shadowBlur=0;
  if(size.id!=='p'){c.font=`600 ${Math.max(11,size.height*.035)}px Arial`;c.globalAlpha=.65;c.fillText(STYLES.find(x=>x[0]===selected)[2].toUpperCase(),tx+available/2,size.height/2+fs*.85);c.globalAlpha=1}
  return canvas;
}
form.onsubmit=async e=>{e.preventDefault();const ie=validateUpload(file),te=validateLabelText($('#label-text').value);$('#image-error').textContent=ie;$('#text-error').textContent=te;if(ie||te)return;setView('loading');try{const response=await fetch('/api/labels/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:source,text:safeText($('#label-text').value),style:STYLES.find(x=>x[0]===selected)[2],instructions:safeText((selected==='personalizado'?$('#custom').value+' ':'')+$('#notes').value,180)})});const data=await response.json();if(!response.ok)throw new Error(data.error);generated=[];for(const size of LABEL_SIZES){generated.push({size,canvas:await compose(size,data.images.find(x=>x.id===size.id)?.background,$('#bleed').checked)})}render(data.mode);setView('results')}catch(err){setView('editor');$('#text-error').textContent=`Não foi possível gerar: ${err.message}`}};
function setView(id){['editor','loading','results'].forEach(x=>$('#'+x).hidden=x!==id);document.querySelectorAll('.steps span').forEach((x,i)=>x.classList.toggle('active',i<=(id==='editor'?0:id==='loading'?1:2)));if(id!=='editor')scrollTo({top:250,behavior:'smooth'})}
function render(mode){const gallery=$('#gallery');gallery.innerHTML='';$('#mode-note').innerHTML=mode==='demo'?'<span class="demo-badge">Modo de demonstração:</span> composição local determinística — nenhuma geração por IA foi realizada.':'Fundos gerados pelo provedor de IA; texto aplicado localmente para máxima legibilidade.';for(const item of generated){const card=document.createElement('article');card.className='result-card';const wrap=document.createElement('div');wrap.className='canvas-wrap';wrap.append(item.canvas);card.append(wrap);const body=document.createElement('div');body.className='card-body';body.innerHTML=`<div class="size-row"><b>Etiqueta ${item.size.name}</b><span>${item.size.cm}</span></div><p class="meta">300 DPI · ${item.size.width} × ${item.size.height} px · área segura de 3 mm</p><div class="card-actions"><button class="secondary view">⛶ Ampliar</button><button class="primary download">↓ Baixar PNG</button></div>`;body.querySelector('.download').onclick=()=>download(item);body.querySelector('.view').onclick=()=>{$('#large-preview').src=item.canvas.toDataURL('image/png');$('#preview-dialog').showModal()};card.append(body);gallery.append(card)}}
function download(item){const a=document.createElement('a');a.download=filenameFor($('#label-text').value,item.size);a.href=item.canvas.toDataURL('image/png');a.click()}
$('#edit').onclick=()=>setView('editor');$('#regenerate').onclick=()=>form.requestSubmit();$('#download-all').onclick=()=>generated.forEach((x,i)=>setTimeout(()=>download(x),i*250));$('#close-dialog').onclick=()=>$('#preview-dialog').close();
